flyway.url=jdbc:mysql://db:3306/dabble?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
flyway.user=root
flyway.password=12345

flyway.locations=classpath:db/migration
# Allow clean
flyway.cleanDisabled=false
