x-args: &args
  args:
    BUILD_NUMBER: ${BUILD_NUMBER:-0} # Bien nhan tu bien moi truong trong Jenkins
    BUILD_TAG: ${BUILD_TAG:-local} # Bien nhan tu bien moi truong trong Jenkins

services:
  server:
    build:
      context: ../server
      dockerfile: Dockerfile.v2
      <<: *args

  admin:
    build:
      context: ../admin
      dockerfile: Dockerfile.v2
      <<: *args

networks:
  app-net: