enum NotificationType {
  SUBSCRIPTION = 'SUBSCRIPTION',
  ACCEPTED = 'ACCEPTED',
  COMMENT = 'COMMENT',
  LIKE = 'LIKE',
  REPLY_COMMENT = 'REPLY_COMMENT',
  SALE_IMAGE = 'SALE_IMAGE',
  FOLLOW_REQUEST = 'FOLLOW_REQUEST'
}

enum TransactionType {
  WITHDRAWAL = 'WITHDRAWAL',
  DEPOSIT = 'DEPOSIT',
  PURCHASE = 'PURCHASE',
  SALE = 'SALE',
  SUBSCRIBE = 'SUBSCRIBE'
}
