export enum NotificationType {
  SUBSCRIPTION = 'SUBSCRIPTION',
  ACCEPTED = 'ACCEPTED',
  COMMENT = 'COMMENT',
  LIKE = 'LIKE',
  REPLY_COMMENT = 'REPLY_COMMENT',
  SALE_IMAGE = 'SALE_IMAGE',
  FOLLOW_REQUEST = 'FOLLOW_REQUEST'
}
